# These are supported funding model platforms
liberapay: tilde.club # Replace with a single Liberapay username
custom: ["https://donate.tilde.club"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
